[package]
name = "pyth_lazer"
version = "0.0.0"
edition = "2024"
published-at = "0x7b502c8a7bcb3915892347f11086745570e759fe9708d03c03accf4c90bbf580"

# TODO: Waiting for upstream PR, change to `wormhole-foundation:main` once it's
# merged: https://github.com/wormhole-foundation/wormhole/pull/4639
[dependencies.Wormhole]
git = "https://github.com/wormhole-foundation/wormhole.git"
subdir = "sui/wormhole"
rev = "sui/mainnet"

[addresses]
pyth_lazer = "0x7b502c8a7bcb3915892347f11086745570e759fe9708d03c03accf4c90bbf580"

[dev-addresses]
pyth_lazer = "0x100"
wormhole = "0x101"
