[package]
name = "Pyth"
published-at = "0xf7114cc10266d90c0c9e4b84455bddf29b40bd78fe56832c7ac98682c3daa95b"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/testnet"

[dependencies.Wormhole]
git = "https://github.com/unmaykr-aftermath/wormhole.git"
subdir = "sui/wormhole"
rev = "sui-testnet-cc029e28"

[addresses]
pyth = "0xe76d8a37d4132278a7a752183e90e04890b9e7d0f6657eadb68821609a2a56a3"
