[package]
name = "Pyth"
version = "0.0.2"

# TODO: Waiting for upstream PR, change to `wormhole-foundation:main` once it's
# merged: https://github.com/wormhole-foundation/wormhole/pull/4639
[dependencies.Wormhole]
git = "git@github.com:AftermathFinance/wormhole.git"
subdir = "sui/wormhole"
rev = "main"

[addresses]
pyth = "_"
